### PR TITLE
Auto install pandas_ta using subprocess 

### PR DESCRIPTION
**Pull request by Charlie-Root**

### CODE REVIEW

**Comment by eSeR1805** [comment]
Can you back out the changes to the protections list? They were tabbed like that to be easier to spot.

**Comment by s0undt3ch** [comment]
Honestly, the strat should just fail to load if missing this import.
Raise `ImportError` with an appropriate message on how to solve it.

**Comment by s0undt3ch** [comment]
This would be easier to spot instead of a log message.

**Comment by eSeR1805** [comment]
Agree with points from @s0undt3ch. Installing a dependency is minimal effort

**Comment by iterativv** [comment]
Also, why this changed the formatting for the whole file ? Could you simply include the relevant changes ?

**Pull request closed without merging**
