### PR TITLE
Add standard protections to buy conditions / Simple candle count check

### PR DESCRIPTION
**Pull request by BillGatesIII**
The latest buy conditions 35, 36, 37 and 38 don't have the standard protections code.

### CODE REVIEW

**Comment by BillGatesIII** [comment]
Somehow my other changes for the simple candle count check also are in this pull request. I wanted to make a separate pr for it; no clue why it is in here.

**Comment by eSeR1805** [comment]
If I'm understanding it correctly simple_candle_count is similar to what I've added with has_downtime_protection.
Holding off merge as protections are now included differently through refactor I'm about to push

**Comment by BillGatesIII** [comment]
ps. It applies to all buy conditions because the check is in the standard protections (in the for loop). But if your additions prevent trades with new pairs in backtesting I'm fine with it of course.

**Comment by iterativv** [comment]
Could you include, for this PR, just the protections for 35-38 ? My current work is without the checks for empty volume.

Later, we decide if to add protections against exchange downtime in live.

**Comment by BillGatesIII** [comment]
Just so I understand you correctly. You do want this commit: [https://github.com/iterativv/NostalgiaForInfinity/pull/45/commits/85d7f2d8ac5bf93941edc6984a83d81142bbb01d](url)
And you don't want the check for enough candles, which is in this commit:
[https://github.com/iterativv/NostalgiaForInfinity/pull/45/commits/5ef686640d4ac4feeff12d7f4f89b47d067724df](url)
Because without it the previous_candle_x in custom_sell could result in an error when a trade is made with a brand new pair.

**Comment by BillGatesIII** [comment]
Wait. Sorry. I just see what @eSeR1805 did. I will  close this PR cause I don't know how to only leave that one commit in it (and it's just four lines of code).

**Pull request closed without merging**
