### PR TITLE
Enhance docker-compose.yaml for Multi-Bot Deployment with Healthcheck Support

### PR DESCRIPTION
**Pull request by seventhsite**
Updated docker-compose.yaml to support running multiple bot instances with unique configurations and added a healthcheck to monitor container status. This makes it easier to manage multiple bots.

### CODE REVIEW

**Comment by davidzhang12138** [comment]
how about api server disable

**Comment by seventhsite** [comment]
Sorry, I didn't understand. Could you please clarify?

**Comment by iterativv** [comment]
Hi, there are some conflicts currently, could you rebase to latest ? Thanks !

**Comment by tolgakaratas** [comment]
FREQTRADE__API_SERVER__LISTEN_PORT for healt check line will be better

**Comment by seventhsite** [comment]
> Hi, there are some conflicts currently, could you rebase to latest ? Thanks !

Done

**Comment by iterativv** [comment]
Also, if you are in discord and you want to let me know your nick there ?

**Comment by seventhsite** [comment]
Sorry, I don't use discord. Only telegram

**Pull request merged**
