### PR TITLE
feat(profit target): add profit target

### PR DESCRIPTION
**Pull request by kevinjulian**
### Objective
To add something like "target profit"

### What's new
- `mark_profit_target`
- `sell_profit_target`
- save & load profit target by pair (file will be saved on `user_data/data-nfi-profit_target_by_pair.json`)

### How to use it
first: mark as profit zone (return pair and mark)
```
def mark_profit_target(self, pair: str, trade: "Trade", current_time: "datetime", current_rate: float, current_profit: float, last_candle, previous_candle_1) -> tuple:
  if self.profit_target_1_enable:
    if (current_profit > 0) and (last_candle['zlema_4_lowKF'] > last_candle['lowKF']) and (previous_candle_1['zlema_4_lowKF'] < previous_candle_1['lowKF']) and (last_candle['cci'] > -100) and (last_candle['hrsi'] > 70):
      return pair, "mark_profit_target_01"
  return None, None
```

second: check how to take the profit
```
def sell_profit_target(self, pair: str, trade: "Trade", current_time: "datetime", current_rate: float, current_profit: float, last_candle, previous_candle_1, previous_rate, previous_sell_reason, previous_time_profit_reached) -> tuple:
  if self.profit_target_1_enable and previous_sell_reason == "mark_profit_target_01":
    if (current_profit > 0) and (current_rate < (previous_rate - 0.005)):
      return True, 'sell_profit_target_01'

  return False, None
```

### CODE REVIEW

**Comment by eSeR1805** [comment]
Check end of file

**Comment by eSeR1805** [comment]
It needs that newline at the end of file. I think it was complaining about something else there

**Comment by eSeR1805** [comment]
Just backtest commenting seems to have failed (maybe because it's running on your branch or smth). But looking at the logs I don't see it affecting BT results. iterativ has some pending stuff so leaving it to him to approve the merge when done so no conflicts occur (hopefully)

**Comment by s0undt3ch** [comment]
I think this is a perfect use case for the newly added cache class....

**Comment by s0undt3ch** [comment]
Also, the logic to get the user data dirctory is user prone since you can pass alternate paths on the FT CLI

**Pull request merged**
