### PR TITLE
Blacklist KRL

### PR DESCRIPTION
**Pull request by MunkeyBalls**
No comment.

### CODE REVIEW

**Comment by Govind-S-B** [comment]
why the blacklist ?

**Comment by Govind-S-B** [comment]
If u think there is a legitimate reason to add this please elaborate and make a new request

**Comment by Govind-S-B** [comment]
ig a lot in the server generally hated its performance (hence re opened the PR)

**Comment by eSeR1805** [comment]
Not sure about this. KRL doesn't look so bad, just that maybe NFI didn't handle it well

**Pull request merged**
