### PR TITLE
Crypto Fear Protection

### PR DESCRIPTION
**Pull request by MrHumanRebel**

### CODE REVIEW

**Comment by eSeR1805** [comment]
It's no use if we can't get historical values, apply as true protections and backtest to see if idea is actually good or not.

**Comment by MrHumanRebel** [comment]
I think dry running test can be done if we want to use this. The only logical use of this protection would be when the fear index is in the Extreme Fear territory. At this level the market is surely dumping. Above this level there is no use of it, it would prevent risky, but profitable trades. At least that is the idea behind it.
What do you guys think?

**Comment by eSeR1805** [comment]
By the time this reaches Extreme Fear market has already dumped. This is a heavily lagging indication. I would rather load up some good coins when in Extreme Fear instead and start selling them when getting close to high greed. In any case not backtestable is no go imo.

**Comment by eSeR1805** [comment]
@MrHumanRebel don't want to discourage you. Try your idea. You can probably merge the latest api response in the main dataframe to use in buy/sell logic through bot_loop_start.

**Pull request closed without merging**
