### PR TITLE
Add printout Strategy name and Version in the logs.

### PR DESCRIPTION
**Pull request by fermosan**

### CODE REVIEW

**Comment by zlov137** [comment]
This already exists. 
freqtrade_NFIX   | 2021-12-09 15:36:49,714 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-decaa24f, strategy_version: v10.8.10', state='RUNNING'

**Comment by eSeR1805** [comment]
Why is this needed? In CLI you have git to tell you what version you're on.

**Comment by ipetko96** [comment]
Please, merge it, this is actually really useful info.

**Comment by fermosan** [comment]
It is good for checking if the updated strategy is loaded correctrly, especially for auto-update environments that will update the strategy one or twice per day.

**Comment by fermosan** [comment]
This has nothing to do with Telegram. I am not even using telegram.  The only purpose of this is to have visibility in the logs which version is loaded like this:
2021-12-09 15:26:50,405 - NostalgiaForInfinityX - INFO - NostalgiaForInfinityX Version v10.8.10

It's not a big deal i think to accept it since it has some use for people that created an auto update procedure and want to verify which version of the strategy is currently loaded.

**Comment by eSeR1805** [comment]
Just switch freqtrade to develop for now if it's urgent, eventually it's going to get merged in stable also :) 
You will have this: `2021-12-10 02:23:05,543 - freqtrade.worker - INFO - Bot heartbeat. PID=20362, version='develop-be6b1f6f8, strategy_version: v10.8.22', state='RUNNING'`

**Pull request closed without merging**
