### PR TITLE
populate_buy_trend function refactor and simplification

### PR DESCRIPTION
**Pull request by lobap**
populate_buy_trend refactor and simplification including the conditions within the main loop which brings some code length savings as well

### CODE REVIEW

**Comment by lobap** [comment]
Should be fixed now and also merged with latest commit (sell signal 1 rework). 

Could you please backtest it against a previous version to see if results are the same? I'm trying to fix my PC after last FT version and currently not able to do it.

**Review by lobap — COMMENTED** [review]
Errors from first PR version are fixed.

**Comment by lobap** [comment]
@eSeR1805 @iterativv last commit should be good, backtested with same results than pre-refactor version

**Comment by eSeR1805** [comment]
I've managed to merge these through https://github.com/iterativv/NostalgiaForInfinity/commit/7af63cce32fd877c3b3357dfcc5c201ce79cbe13. Would have done it through this but tbh I'm not that good at git :(

**Comment by lobap** [comment]
Great! Shall i close this PR then?

**Comment by eSeR1805** [comment]
Closing it. Thanks for your work <3

**Pull request closed without merging**
