### PR TITLE
add update_nfx file

### PR DESCRIPTION
**Pull request by sembsa**
I added a file that, when launched, updates the NFX policy file and sends a notification to our bot. In the file you need to change the variables at the top. The file is specially made to be called by some other action, we don't necessarily need an automatic update.

### CODE REVIEW

**Comment by cazzeken** [comment]
Nice. Instead of restarting the docker container, you could also curl the rest_client.py like this to reload the config. python3 rest_client.py --config ft01.json reload_config

**Comment by iterativv** [comment]
Could you change the language inside the script to English, maybe ?

**Comment by sembsa** [comment]
> 

I prefer a solution that restarts the container

**Comment by sembsa** [comment]
> Could you change the language inside the script to English, maybe ?

I forgot

**Comment by iterativv** [comment]
> > Could you change the language inside the script to English, maybe ?
> 
> I forgot

Also, if you are on discord, could you let me know your nick there ?

**Pull request merged**
