### PR TITLE
Automate the refactoring of HO into raw values

### PR DESCRIPTION
**Pull request by anasyusef**
### Overview

Script to automate transforming HO values into raw values. E.g.

```buy_dip_threshold_10_1 = DecimalParameter(0.001, 0.05, default=0.015, space='buy', decimals=3, optimize=False, load=True)```

Would be transformed to:

```buy_dip_threshold_10_1 = 0.015```

### Command reference
```
usage: ho_to_raw_codemod.py [-h] [--input INPUT_PATH] [--output OUTPUT_PATH]

optional arguments:
  -h, --help            show this help message and exit
  --input INPUT_PATH, -i INPUT_PATH
                        Strategy path
  --output OUTPUT_PATH, -o OUTPUT_PATH
                        Output of transformed file
```

The script has a simple CLI, where it accepts two arguments, the input, which would be the strategy path and the output,  which is the path of the transformed file. E.g.

`python codemods/ho_to_raw_codemod.py -i NostalgiaForInfinityNext.py -o NostalgiaForInfinityNext_Raw.py`

### CODE REVIEW

**Comment by eSeR1805** [comment]
Started tests and Pre-Commit fails with:
-    assert transform_code(code_input.strip()) == expected_output.strip()
\ No newline at end of file
Breafly read that that's mandatory for some reasons. You probably know more than me on this

**Comment by eSeR1805** [comment]
Also would it be straighforward that at least one backtest to be issue to compare original to raw versions. I guess that makes for a more complicated testcase. Your implementation should suffice anyway as it's straightforward checking just the codemod function.

**Comment by anasyusef** [comment]
> Started tests and Pre-Commit fails with:
> 
> * assert transform_code(code_input.strip()) == expected_output.strip()
>   \ No newline at end of file
>   Briefly read that that's mandatory for some reasons. You probably know more than me on this

I just made a few changes to address linter issues

**Comment by anasyusef** [comment]
> Also would it be straighforward that at least one backtest to be issue to compare original to raw versions? I guess that makes for a more complicated testcase. Your implementation should suffice anyway as it's straightforward checking just the codemod function.

I'm still not sure how the raw versions should be released. Would it only be applied and released whenever there's a new version, or should it be updated automatically after a new commit, or would it just be used for backtesting?

For now, I'm releasing it as a tool should anyone want to use it

**Comment by eSeR1805** [comment]
I guess it should run only for new releases. Giving people the option to use that instead of the original. For live/dry it doesn't matter that much but backtests would probably have a slight boost in run duration.
Black is still complaining?

**Comment by anasyusef** [comment]
> I guess it should run only for new releases. Giving people the option to use that instead of the original. For live/dry it doesn't matter that much but backtests would probably have a slight boost in run duration.
> Black is still complaining?

Sure. I would have to make a different PR for that.

As for the linter issues. For some reason, the pre-commit hook wasn't getting applied. I had to apply it manually. Should be good now

**Comment by eSeR1805** [comment]
This looks good. Nice work!

**Comment by s0undt3ch** [comment]
I'll add some notes about pre-commit to the readme when I can.

**Pull request merged**
